server:
  port: 8080
spring:
  data:
    mongodb:
      host: 127.0.0.1
      username: root
      password: root
      port: 27017
      database: mongo
  servlet:
    multipart:
      max-file-size: 100MB